name: Collect Edinburgh Bus Data
 
on:
  workflow_dispatch:
 
  schedule:
    - cron: "*/5 * * * *"
 
permissions:
  contents: write
 
jobs:
  collect:
 
    runs-on: ubuntu-latest
 
    steps:
 
      - name: Get repository
        uses: actions/checkout@v6
 
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
 
      - name: Install Python packages
        run: pip install requests
 
      - name: Collect bus data
        env:
          BUS_API_KEY: ${{ secrets.BUS_API_KEY }}
        run: python collect.py


        -name: Save collected data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add bus_observations.csv
          git commit -m "Add bus observation" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
 
